config/routes.rb
Myapp::Application.routes.draw do
  
  get "sessions/signin", as: :signin
  post "sessions/signin" => 'sessions#create'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  root to: 'home#index'
  get "aboutus/index", :as => 'aboutus'
  get "discount/index", :as => 'discount'
  get "mysavings/index", :as => 'savings'
  get 'mysavings/create', :as => 'add'
  get 'mysavings/remove', :as => 'remove'
  get "prescription/index", :as => 'medicines'
  get "prescription/autocomplete", :as => 'autocomplete'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
 validates :name, :presence => true
 validates :dispense, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/website.rb
class Website < ActiveRecord::Base
validates :name, :presence => true
validates :url, :presence => true
validates :active, :presence => true

end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
layout 'home'
  def index
  	
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale, :set_query
 
  def set_locale
   I18n.locale = params[:locale] || I18n.default_locale
  end

  def set_query
  	@mains = Medicine.search(params[:q])
  end

end

app/controllers/discount_controller.rb
class DiscountController < ApplicationController
layout 'home'
  def index
  	 @search = Website.search(params[:q])
  	 @search.sorts = 'name' if @search.sorts.empty?
     @websites = @search.result.page(params[:page]).per(20)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

app/controllers/mysavings_controller.rb
class MysavingsController < ApplicationController
layout 'home'
  def index
  	@mycart = cookies[:cart].nil? ? [] : cookies[:cart].split("&")
	  @savings = Medicine.search({id_in: @mycart}).result unless @mycart.empty?
  end
  def create 
  	mycookies = cookies[:cart].nil? ? [] : cookies[:cart].split("&")
  	mycookies << params[:id] unless params[:id].nil?
  	cookies[:cart] = mycookies
  	redirect_to request.referer
  end
  def remove
  	@mycart = cookies[:cart].nil? ? [] : cookies[:cart].split("&")
  	@mycart.delete(params[:id])
  	cookies[:cart] = @mycart
  	redirect_to request.referer
  end
end

app/controllers/prescription_controller.rb
class PrescriptionController < ApplicationController
layout 'home'
  def index
    @search = Medicine.search(params[:q])
    @mains = Medicine.search(params[:q])
    @search.sorts = 'name' if @search.sorts.empty?
    @medicines = @search.result.page(params[:page]).per(4)
    @search.build_condition
    @mycart = cookies[:cart].nil? ? [] : cookies[:cart].split("&")
  end
  def autocomplete
  	@mysearch = Medicine.search({name_cont: params[:query]}).result.pluck(:name)
  	@render = {query: params[:query],suggestions: @mysearch, data: @mysearch}
  	render json: @render
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
layout 'home'
  def signin
  	
  end
  def create

  end
end

app/helpers/aboutus_helper.rb
module AboutusHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discount_helper.rb
module DiscountHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mysavings_helper.rb
module MysavingsHelper
end

app/helpers/prescription_helper.rb
module PrescriptionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/aboutus/index.html.erb
<div class="render">
	<div class="site_container">
		<h2 class="text-left">About Us</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc maximus vehicula gravida. Nunc faucibus sapien a risus tempus commodo. Duis a dictum massa, et cursus elit. Pellentesque feugiat, magna a mattis semper, urna neque tristique orci, sit amet tincidunt odio odio at enim. In ultricies lectus risus, et rhoncus libero congue at. Fusce faucibus eros at risus mattis sodales. Donec ac turpis in dolor scelerisque viverra vitae in nunc. Ut ac arcu sed libero fringilla auctor. Suspendisse luctus velit vitae ligula suscipit, porta egestas arcu elementum. Cras faucibus metus at nisl efficitur tempor. Integer accumsan sodales libero, vitae dignissim eros porta at. Nullam semper vulputate luctus. Mauris quis ipsum odio. Sed sit amet placerat tortor. Ut ut quam nulla. In hac habitasse platea dictumst.</p>
             <p>Nulla eget neque non massa ullamcorper iaculis. Curabitur blandit magna et nibh mattis, et dictum leo rutrum. Nulla facilisi. Etiam tincidunt metus vehicula, aliquet felis molestie, faucibus justo. Morbi rhoncus luctus ante. Phasellus tincidunt nisi magna, id lobortis eros luctus vitae. In placerat ullamcorper urna in egestas. Cras nec luctus ipsum, eget hendrerit mi. Nulla bibendum eros id ex euismod, in blandit enim scelerisque. Donec in varius felis, ac posuere nisi. Phasellus dapibus dolor lacus, vel venenatis turpis egestas et. Quisque suscipit tincidunt arcu imperdiet malesuada. Proin vestibulum quam sed dui molestie, quis hendrerit urna hendrerit. Morbi blandit sollicitudin convallis. Suspendisse potenti. Quisque ligula sem, condimentum ac congue porta, aliquam sed augue.</p>                
             <p>Cras efficitur diam sit amet eros sollicitudin mattis. Aenean posuere accumsan malesuada. Morbi in vehicula turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus hendrerit pharetra magna quis suscipit. Proin feugiat velit nec mattis pretium. Aliquam sollicitudin mollis magna, luctus tempus nunc viverra non. Sed urna est, rutrum et eleifend vel, mattis eu neque. Cras nec fermentum sapien. Aliquam erat volutpat. Aliquam erat volutpat. Praesent ultrices facilisis augue, quis ultricies velit malesuada vel. Ut vel dignissim arcu. Sed nec facilisis sem. Sed hendrerit varius magna quis suscipit. </p>

                      <ul class="aboutus_list">
                      
                       <li><%=image_tag 'aboutus_imgs_05.png', :class => 'res_images' %></li>
                       <li><%=image_tag 'aboutus_imgs_07.png', :class => 'res_images' %></li>
                       <li><%=image_tag 'aboutus_imgs_09.png', :class => 'res_images' %></li>
                      
                      
                      </ul>


                 <p>Morbi a commodo eros. Phasellus ornare arcu ante, et malesuada mi ullamcorper vitae. Mauris suscipit quis felis nec cursus. Nunc vitae urna neque. Sed auctor erat non tincidunt imperdiet. Curabitur eu sapien quis justo aliquam maximus. Praesent lacinia tincidunt nisi.</p>
                 <p>Maecenas sit amet justo porta, volutpat sapien ut, pulvinar mi. Aenean non mi ullamcorper lacus ornare blandit. Sed facilisis venenatis efficitur. Nam vulputate lobortis sagittis. Aenean eget elementum diam. Donec imperdiet bibendum velit, aliquet mollis augue gravida ac. Nulla a dui non purus condimentum mollis vitae et nunc. Duis aliquam, odio non iaculis gravida, tellus erat volutpat massa, et bibendum nulla nunc vel elit. Cras eget tincidunt turpis. Praesent a eleifend orci, ut vehicula tellus. Donec hendrerit sed est in iaculis. Integer sed mi dictum, scelerisque justo id, accumsan purus. Praesent bibendum suscipit fermentum. Mauris ullamcorper arcu sit amet urna porta pulvinar. </p>
                 <p>Nulla eget neque non massa ullamcorper iaculis. Curabitur blandit magna et nibh mattis, et dictum leo rutrum. Nulla facilisi. Etiam tincidunt metus vehicula, aliquet felis molestie, faucibus justo. Morbi rhoncus luctus ante. Phasellus tincidunt nisi magna, id lobortis eros luctus vitae. In placerat ullamcorper urna in egestas. Cras nec luctus ipsum, eget hendrerit mi. Nulla bibendum eros id ex euismod, in blandit enim scelerisque. Donec in varius felis, ac posuere nisi. Phasellus dapibus dolor lacus, vel venenatis turpis egestas et. Quisque suscipit tincidunt arcu imperdiet malesuada. Proin vestibulum quam sed dui molestie, quis hendrerit urna hendrerit. Morbi blandit sollicitudin convallis. Suspendisse potenti. Quisque ligula sem, condimentum ac congue porta, aliquam sed augue.</p>
                 <p>&nbsp;</p>

	</div>
</div>

app/views/discount/_paginate.html.erb
<div class="query__pag">
	<%=paginate @websites %>
</div>

app/views/discount/index.html.erb
<div class="sub_banner">
	<div class="site_container">
		<%=render :partial => "home/search" %>
	</div>
</div>



<div class="render">
	<div class="site_container">
		<h2 class="text-left">Discount Pharmacy Websites</h2>
		<%unless @websites.empty? %>
		   <%= render :partial => 'discount/paginate' %>
			
			<!-- Responsive Table -->
			<div class="table-responsive">
				<table class="form__results">
		        <thead>
		          <tr>
		            <th><%=sort_link @search,:name, "Name" %></th>
		            <th><%=sort_link @search,:ing, "Phone Number" %></th>
		            <th><%=sort_link @search,:country_name, "Active" %></th>
		            <th><%=sort_link @search,:dispense, "Fees" %></th>
		          </tr>
		        </thead>
		        <tbody>
		          <%@websites.each do |web| %>
		            <tr>
		              <td class="renderbd"><%= web.name %></td>
		              <td class="renderbd"><%= web.pno %></td>
		              <td class="renderbd"><%= web.active %></td>
		              <td class="renderbd"><%= web.fees %></td>
		            </tr>
		          <%end %>
		        </tbody>
		      </table>
		  </div>
		  <%= render :partial => 'discount/paginate' %>
		<%else %>
		          <p>Sorry! No results found </p>
		<%end %>
	</div>
</div>

app/views/home/_paginate.html.erb
<div class="query__pag">
	<div class="val"><span>Page 1 of 50</span></div>
	<ul class="pagination">
	  <li><a href="#">&laquo;</a></li>
	  <li><a href="#">1</a></li>
	  <li><a href="#">2</a></li>
	  <li><a href="#">3</a></li>
	  <li><a href="#">4</a></li>
	  <li><a href="#">5</a></li>
	  <li><a href="#">&raquo;</a></li>
	</ul>
</div>

app/views/home/_query.html.erb
<div class="query_form">
<div class="form__label">
  Filter
</div>  
<div class="form__content">
<%= search_form_for @search, :class => 'form-inline' do |f|%>
	<div class="thr__ct">
			<%= f.condition_fields do |c| %>
				<div class="box">
				<%= c.attribute_fields do |a| %>
			 		<%= a.attribute_select({:include_blank => true}, {:class => 'form-control', :style => "height:inherit;padding:inherit"})%>
				<%end %>
				<%= c.predicate_select({:foo_cont => true},{ :class => 'form-control', :style => "height:inherit;padding:inherit"})%>
				<%= c.value_fields do |v| %>
					<%= v.text_field :value, :class => 'form-control' %>
				<%end%>
				</div>
			<%end%>	
	</div>
	<div class="thr__gen">
		<%= f.submit "Search", :class => 'btn'%>
	</div>
	
<%end %>
</div>
</div>

app/views/home/_search.html.erb
<%= search_form_for @mains, :id => 'search-form' do |f| %>
  <div class="col-sm-10 col-xs-12 col-sm-offset-1">
    <div class="input-group">
    <!-- <input type="text" placeholder="Search Drugs....autocomplete Ajax" name="autocomplete-ajax" id="autocomplete-ajax" class="form-control style-2" autocomplete="off"> -->
     <%= f.search_field :name_cont, :class => 'form-control style-2', :id => 'autocomplete-ajax' %>
    <span class="input-group-btn">
      <button class="btn" type="submit"><i class="fa fa-search"></i></button>
    </span>
    </div>
    <div class="adv_search" style="display: block;"><a href="#">Advanced search</a></div>

  </div>
<%end %>

app/views/home/index.html.erb
<div class="banner">
	<div class="site_container">
		<p class="banner__content"><span style='visibility:hidden'>a&#768;</span><%=t 'home.compareone' %><br><%=t 'home.comparetwo' %></p>
		<%=render :partial => "home/search" %>
	</div>
</div>
<div class="welcome__message">
	<div class="divider_top"></div>
  <div class="site_container">
  	<h2 class="text-left"><%=t "home.welcome" %></h2>
		<p><%=t "home.lorem1" %></p>		
		<p><%=t "home.lorem2" %></p>
		<a href="#" class="siteprimary"><%=t "home.signupnow" %>
    </a>
	</div>
</div>
<div class="render">
<div class="site_container">
	<h2><%=t "home.loproducts" %></h2>
	<div class="table-responsive">
		<table class="form__results">
        <thead>
          <tr>
            <th><%=t "home.nameofmed" %><a href=""><span class="caret"></span></a></th>
            <th><%=t "home.activeing" %></th>
            <th><%=t "home.ctor" %><a href=""><span class="caret"></span></a></th>
            <th><%=t "home.dis" %></th>
            <th><%=t "home.rx" %>?</th>
            <th><%=t "home.gen" %>?</th>
            <th><%=t "home.perunit" %><a href=""><span class="caret"></span></a></th>
            <th><%=t "home.buy" %></th>
            <th><%=t "home.add" %><br><%=t "home.worksheet" %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="renderbd">Atorvastatin 20mg  (Generic alternative to Lipitor 20mg)</td>
            <td class="renderbd">Atorvastatin</td>
            <td>Australia </td>
            <td>Mauritius</td>
            <td class="renderbd">Yes</td>
            <td class="renderbd">No</td>
            <td class="renderbd">$0.13 per Tablet</td>
            <td class="renderbd">Link</td>
            <td><a href="#"><span class="label label-default" style='cursor:pointer'>Add</span></a></td>
          </tr>
          <tr>
            <td class="renderbd">Atorvastatin 20mg  (Generic alternative to Lipitor 20mg)</td>
            <td class="renderbd">Atorvastatin</td>
            <td>Australia </td>
            <td>Mauritius</td>
            <td class="renderbd">Yes</td>
            <td class="renderbd">No</td>
            <td class="renderbd">$0.13 per Tablet</td>
            <td class="renderbd">Link</td>
            <td><a href="#"><span class="label label-default" style='cursor:pointer'>Add</span></a></td>
          </tr>
          <tr>
            <td class="renderbd">Atorvastatin 20mg  (Generic alternative to Lipitor 20mg)</td>
            <td class="renderbd">Atorvastatin</td>
            <td>Australia </td>
            <td>Mauritius</td>
            <td class="renderbd">Yes</td>
            <td class="renderbd">No</td>
            <td class="renderbd">$0.13 per Tablet</td>
            <td class="renderbd">Link</td>
          	<td><a href="#"><span class="label label-default" style='cursor:pointer'>Add</span></a></td>
          </tr>
        </tbody>
      </table>
	</div>
</div>
</div>
<div class="testimonials">
<div class="site_container">
	<h2><%=t "home.testimonials" %></h2>
	<div class="tes_cnt">
		<blockquote>
      <p><%=t "home.testlorem" %></p>
    </blockquote>
      <p><%=t "home.name" %> XXXXX</p>  
  </div>
</div>	
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="site_container">
    <div class="footer__top">
    <div class="footer--boxes">
      <h3>QUICK LINKS</h3>
      <ul id="footer__quicklinks">
        <li><%= link_to  I18n.t("nav.home"), root_url %></li>
        <li><%= link_to I18n.t("nav.pres"), medicines_path %></li>
        <li><%= link_to I18n.t("nav.dis"), discount_path  %></li>
        <li><%= link_to I18n.t("nav.us"), aboutus_path %></li>
        <li><%= link_to I18n.t("nav.work"), savings_path  %></li>
      </ul>
    </div>
    <div class="footer--boxes">
      <h3>
        CONTACT US
      </h3>
      <p>Fusce dapibus, tellus commodo, tortor mauris condimentum utellus fermentum, porta sem malesuada magna. </p>
      <address>
        <strong>Moonshine</strong><br>
        Street No: 14/05 <br>Light City, Jupiter
        0247 541 65 87<br>
        <abbr title="Email">Email:</abbr> support@longwave.com
      </address>
    </div>
    <div class="footer--boxes">
      <h3>GET IN TOUCH</h3>
      <%= render :partial => "layouts/newsletter" %>
    </div>
    </div>
    <hr>
    <div class="footer__base">
      <div class="nav__soc">
        <ul class="footer">
         <li><a href="#" class="facebook"><i class="fa fa-facebook fa-lg"></i></a></li>
         <li><a href="#" class="twitter"><i class="fa fa-twitter fa-lg"></i></a></li>
         <li><a href="#" class="googleps"><i class="fa fa-google-plus fa-lg"></i></a></li>
         <li><a href="#" class="rss"><i class="fa fa-rss fa-lg"></i></a></li>
        </ul>
      </div>
      <p>© 2014 Prescription Saving Solutions.. All Rights Reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="site_container">
       <div class="header__logo">
        <h1>Prescription Saving Solutions</h1>
        <h4>Affordable healthcare is a basic human right</h4>
       </div>
       <div class="header__right">
           <%= render :partial => "layouts/localization" %>
           <ul class="header--login">
              <li><a href="#">Sign Up</a></li>
              <li><%=link_to "Sign in", signin_path %></li>

           </ul>
           <ul class="header--info">
             <li>
              <a href="#">000-000-0000</a>
             </li>
              <li>
              <a href="#">info@prescription.com</a>
             </li>
           </ul>
        </div>
  </div>
</header>
<script>

</script>

app/views/layouts/_nav.html.erb
<nav>
<div class="site_container">
      <ul class="nav__menu">
        <li><%= link_to  I18n.t("nav.home"), root_url %><i class='fa fa-caret-up'></i></li>
        <li class="bigger"><%= link_to I18n.t("nav.pres"), medicines_path %></li>
        <li class="bigger"><%= link_to I18n.t("nav.dis"), discount_path  %></li>
        <li><%= link_to I18n.t("nav.us"), aboutus_path %></li>
        <li class="bigger"><%= link_to I18n.t("nav.work"), savings_path  %></li>
      </ul>
      <div class="nav__soc">
        <ul>
         <li><a href="#" class="facebook"><i class="fa fa-border fa-facebook fa-lg"></i></a></li>
         <li><a href="#" class="twitter"><i class="fa fa-border fa-twitter fa-lg"></i></a></li>
         <li><a href="#" class="googleps"><i class="fa fa-border fa-google-plus fa-lg"></i></a></li>
         <li><a href="#" class="rss"><i class="fa fa-border fa-rss fa-lg"></i></a></li>
        </ul>
      </div>
 </div>
</nav>

app/views/layouts/_newsletter.html.erb
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" placeholder="Name">
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="message" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-10">
      <textarea class="form-control" id="message" placeholder=''></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigitalOcean Rails Application</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render :partial => "layouts/header" %>
<%= render :partial => "layouts/nav" %>
	 <p class="notice"><%= notice %></p>
	 <p class="alert"><%= alert %></p>
     <%= yield %>
<%= render :partial => "layouts/footer" %>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Prescription Savings</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "screen", "data-turbolinks-track" => true %>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="Prescription savings"/>
  
  <meta name="description" content="Find Drugs">
  <meta name="keywords" content="drugs,finder,prescription,savings">
  <meta name="author" content="Media3 International Pvt. Ltd.">
  <!-- Jquery Fetch  -->
  <%= stylesheet_link_tag    "jquery-ui", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "autocomplete", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<%= render :partial => "layouts/header" %>
<%= render :partial => "layouts/nav" %>
     <%= yield %>
<%= render :partial => "layouts/footer" %>
<script>
 $('#autocomplete-ajax').autocomplete({
    serviceUrl: '/prescription/autocomplete',
    onSelect: function (suggestions) {
        console.log(suggestions.data)
    },
    onSearchComplete: function(query, suggestions){
      console.log("testing");
      console.log(query);
      console.log(suggestions);
    }
});
</script>
</body>
</html>

app/views/mysavings/index.html.erb
<div class="sub_banner">
	<div class="site_container">
		<%=render :partial => "home/search" %>
	</div>
</div>

<div class="render">
	<div class="site_container">
		<h2 class="text-left">My Savings Worksheet</h2>
		<!-- Responsive Table -->
		<div class="top_buttons">
			<a href="" class="red"><span class="label label-danger" style='cursor:pointer'>Remove all</span></a>
			<a href="#" onclick = "PrintDiv();" class="red"><span class="label label-success" style='cursor:pointer'><i class='fa fa-print'></i>&nbsp;&nbsp;&nbsp;Print</span></a>
		</div>
	<%if @savings.nil? %>		
		<hr>
          <p><i class='fa fa-warning' style='color:#f0ad4e;'></i>Sorry! No results found </p>
	<%else %>
		<div class="table-responsive" id='ptr'>
			<table class="form__results">
	        <thead>
	          <tr>
	            <!-- <th><%=t "savings.sno" %></th> -->
	            <th><%=t "savings.product" %></th>
	            <th><%=t "home.ctor" %><a href=""><span class="caret"></span></a></th>
	            <th><%=t "savings.price" %></th>
	            <th style="text-align:center" class="remove_lk"><%=t "savings.remove" %>?</th>
	          </tr>
	        </thead>
	        <tbody>
	          <%@savings.each do |med| %>
	          <tr>
				<td class="renderbd"><%=med.name %></td>
	            <td class="renderbd"><%=med.country_name %></td>
	            <td class="renderbd">$<%=med.price %></td>
	            <td class="renderbd remove_lk"><a href="<%=remove_path %>?id=<%=med.id %>" class="red"><span class="label label-default" style='cursor:pointer'>Remove</span></a></td>
	          </tr>
	          <%end %>
	        </tbody>
     	 </table>
		</div>
	<%end %>
	</div>
</div>

<script type="text/javascript">     
function PrintDiv() {
   var divToPrint = document.getElementById('ptr');
   var popupWin = window.open('', '_blank', 'width=700,height=1200');
   popupWin.document.open();
   popupWin.document.write('<html><head><link rel="stylesheet" type="text/css" media="print" href="/assets/screen.css"><style>.remove_lk{display:none}</style></head><body onload="window.print()">' + divToPrint.innerHTML + '</html>');
   popupWin.document.close();
}
</script>

app/views/prescription/_paginate.html.erb
<div class="query__pag">
	<!-- <div class="val"><span>Page  <%= params[:page] ? params[:page] : 1 %> of </span></div> -->
	<%=paginate @medicines %>
</div>

app/views/prescription/index.html.erb
<div class="sub_banner">
	<div class="site_container">
		<%=render :partial => "home/search" %>
	</div>
</div>

<div class="render">
	<div class="site_container">
	<h2 class="text-left">Prescription Savings Finder</h2>
  <!-- Query form -->
  <%unless @medicines.empty? %>
   <%= render :partial => 'prescription/paginate' %>
   <%= render :partial => 'home/query' %>
	<!-- Responsive Table -->
	<div class="table-responsive">
		<table class="form__results">
        <thead>
          <tr>
            <th><%=sort_link @search,:name, "#{t 'home.nameofmed'}" %></th>
            <th><%=sort_link @search,:ing, "#{t 'home.activeing'}" %></th>
            <th><%=sort_link @search,:country_name, "#{t 'home.ctor'}" %></th>
            <th><%=sort_link @search,:dispense, "#{t 'home.dis'}" %></th>
            <th><%=sort_link @search,:rx, "#{t 'home.rx'}" %></th>
            <th><%=sort_link @search,:generic, "#{t 'home.gen'}" %></th>
            <th><%=sort_link @search,:price, "#{t 'home.perunit'}" %></th>
            <th><%=sort_link @search,:buy, "#{t 'home.buy'}" %></th>
            <th><%=t "home.add" %><br><%=t "home.worksheet" %></th>
          </tr>
        </thead>
        <tbody>
          <%@medicines.each do |med| %>
            <tr>
              <td class="renderbd"><%= med.name %></td>
              <td class="renderbd"><%= med.ing %></td>
              <td class="renderbd"><%= med.country_name %></td>
              <td class="renderbd"><%= med.dispense %></td>
              <td class="renderbd"><%= med.rx %></td>
              <td class="renderbd"><%= med.generic %></td>
              <td class="renderbd">$<%=med.price %> per Tablet</td>
              <td class="renderbd"><%=med.buy %></td>
            	<td>
                <%if @mycart.include?("#{med.id}")%>
                  <a href="#"><span class="label label-success" style='cursor:pointer'>Added</span></a>
                <%else %>
                  <a href="<%= add_path%>?id=<%= med.id%>"><span class="label label-default" style='cursor:pointer'>Add</span></a>
                <%end %>
              </td>
            </tr>
          <%end %>
        </tbody>
      </table>
  </div>
  <%= render :partial => 'prescription/paginate' %>
   <%else %>
   <hr>
          <p><i class='fa fa-warning' style='color:#f0ad4e;'></i>Sorry! No results found </p>
    <%end %>
	</div>
</div>